### ISSUE TITLE
autoscaling

### ISSUE THREAD

**Issue by markfisher** [markfisher/sk8s#10]
For the HandlerPool dispatch strategy, we currently scale from 0 to 1 upon first invocation of a Function. We also need to scale from 1..N (and down) according to configured parameters (this could possibly happen via HPA in cases where that granularity/latency is sufficient). Also the running Functions should be able to shut themselves down after a configurable idle period (and/or possibly a max-messages threshold). The dispatcher would handle the scaled-to-0 case exactly as it handles the initial invocation case. We'll need to take topic partitions into account as well.

**Comment by ericbottard** [comment]
Related concepts:
* https://kubernetes.io/docs/tasks/configure-pod-container/quality-service-pod/
* https://kubernetes.io/docs/tasks/configure-pod-container/opaque-integer-resource/
* https://kubernetes.io/docs/tasks/run-application/configure-pdb/

**Comment by markfisher** [comment]
If the Function app is going to shut itself down, it would need to be Job so it could inidcate *complete* upon exiting with a 0 status (since otherwise the restartPolicy would be "Always"). If the dispatcher is managing the scale-to-0 case instead, it could be handled by updating the controlling ReplicaSet.

**Comment by markfisher** [comment]
...and the Function app cannot switch to be managed as a Job (or be updated to have a restartPolicy for any value other than "Always") if it's initially created via a Deployment/ReplicaSet as it is in this case since we're borrowing each Pod from a pool.

**Comment by ericbottard** [comment]
See #8 for implementation approach
