### ISSUE TITLE
support Flux input and output for Java Functions

### ISSUE THREAD

**Issue by markfisher** [markfisher/sk8s#136]
Currently we have two class loaders, one for the app (the one the JVM was launched on), and one for the functions. The function classloader has a null parent, so it is nicely isolated, and you can use whatever types you like inside it (they get marshalled and unmarshalled into JSON by the main app using their own classloader). But you can't pass types from functions over to the main app, in particular `Flux`. We want to support users writing `Function<Flux<...>, Flux<...>>`.

There are various options here, some of which might have compromises (e.g. to do with startup time, and flexibility of the programming model for users). 

1. Do nothing to the existing code (i.e. null parent in function), but add reactor to the boot classpath.
2. Create a classloader with just reactor, use it as a parent for both the app and the functions.
3. Make the app classloader the parent of the function class loader.
4. Scrap the extra classloader and make everyone swim in the same soup.

Option 3. is a terrible idea because it means that user code cannot use any of the classes in the app (all of Spring Boot for instance). Some users might not need that, but we restrict their options a lot.

Option 4. is also a probably terrible idea because user functions could easily break the invoker app, or vice versa, by providing features or versions of features that are incompatible. It's also really hard (maybe impossible) to support runtime function registration, which we will need for a warm start. It's really simple though.

Both of the other approaches will work, and there is no performance penalty.

Option 1. is quick and dirty and relies on a `-X` option in the JVM. It is hard to test (e.g. you won't be able to test it from the IDE without setting up a custom launcher that creates the right classpath).

Option 2. is more code and it's harder to debug, but seems like less of a hack, possibly, except that when you get down to it you find that you have to do things like reflective hacks in `java.net.URL` for instance.

In both approaches the user has to be coding against the same version of reactor (or at least one which is compatible with the version that the function invoker uses and installs in the class loader hierarchy).

The other feature of the current code that we might want to change is that it has a very dumb instantiation strategy. Each function class is loaded and then instantiated reflectively (default constructor). No dependency injection, no Spring Boot goodness. To change that we need another layer of code in both approaches, e.g. to create a Spring Boot application and extract the functions from it. That might also be by name, instead of by class. The `function.uri` has to change its format to accommodate the additional options. Code in the invoker gets more complicated and has more branches.

I suggest we open another issue to track changes required to hook up an infinite stream (as opposed to an HTTP POST). Leave this one to be about just the class loading and possibly instantiation strategies.

**Comment by markfisher** [comment]
resolved by #159

**Comment by dsyer** [comment]
Just for the sake of clarity #159 was an implementation of option 2. And the default isolation is option 2 (not option 0, as implied by the description).
