### ISSUE TITLE
ensure Go docker images run on GKE

### ISSUE THREAD

**Issue by markfisher** [markfisher/sk8s#148]
We know that using the `alpine` base rather than `FROM scratch` works, but we should investigate what exactly is missing in the scratch case so that we can continue to deliver the lightest possible artifact. This article might help (worth first checking if it's the certs): https://medium.com/@kelseyhightower/optimizing-docker-images-for-static-binaries-b5696e26eb07

**Comment by markfisher** [comment]
Seems we should start by adding this to the `Dockerfile` (while maintaining `FROM scratch`):

```
ADD ca-certificates.crt /etc/ssl/certs/
```

This is another good reference: https://blog.codeship.com/building-minimal-docker-containers-for-go-applications/

**Comment by freynca** [comment]
Adding `-ldflags "-linkmode external -extldflags -static"` to the `go build` step produces a working image.

Source for the change: https://github.com/moby/moby/issues/26495#issuecomment-280330831

**Comment by freynca** [comment]
https://github.com/ericbottard/sk8s-http-gateway/pull/10
https://github.com/ericbottard/sk8s-topic-controller/pull/7
https://github.com/ericbottard/function-sidecar/pull/12

**Comment by freynca** [comment]
Results:
https://ci.faas.to.cf-app.com/teams/pfs/pipelines/sk8s/jobs/run-sk8s-system-tests-gke/builds/7
https://ci.faas.to.cf-app.com/teams/pfs/pipelines/sk8s/jobs/run-sk8s-system-tests-kubo/builds/10

Closing.
