### ISSUE TITLE
support sync request/reply

### ISSUE THREAD

**Issue by markfisher** [markfisher/sk8s#5]
The gateway should accept a callback request header that could then be invoked when a downstream Function has no output binding (end of a pipeline). This would enable 2 styles of request/reply clients of the gateway:
1. streaming request/reply: passing the same callback URL for each request sent (e.g. rendering responses without concern for request correlation or order in a single-page app)
2. synchronous 1:1 correlation: passing a unique callback URL for each request and waiting for the correlated response (up to a configurable timeout)

**Comment by ericbottard** [comment]
Implemented via bc7906ff74fccfd563230182c7315629287c1bd8 and later in the Go gateway
