### ISSUE TITLE
spike: topic monitor

### ISSUE THREAD

**Issue by markfisher** [markfisher/sk8s#8]
monitor a topic's partitions and per-function consumer lag, via sliding windows over the joined streams of produced messages (using a separate "monitor" consumer group) and consumer offsets (for each inactive function's consumer group), and based on thresholds for "queue depth" and/or time, trigger the deployment of an active subscriber as the function handler... at that point the monitor can relinquish control for that particular function/partition-range, but after a configurable idle-time that handler could deactivate itself, at which point the monitor would need to resume control

**Comment by ericbottard** [comment]
Implemented via FunctionMonitor + LagTracker
