### ISSUE TITLE
optimize startup of java-function-invoker

### ISSUE THREAD

**Issue by markfisher** [markfisher/sk8s#84]
given how constrained our environment is, we should be able to avoid a lot of unnecessary initialization including classpath scanning, post-processors, etc. (we could also reduce dependencies)

**Comment by ericbottard** [comment]
Shall we close this, or do we want to push further?

**Comment by dsyer** [comment]
We should document what we did and measure it, so we can assess regressions or improvements. I made some benchmarks. Will post results soon.

For the record, classpath scanning is (really) *never* the problem. Perpetuating the myth is a bad idea.

**Comment by markfisher** [comment]
I agree we should document our benchmarks as a reference. I'd like to know if @dsyer thinks there's more to do in the short term as well.

re: classpath scanning - that's good to know, Dave.

**Comment by dsyer** [comment]
#139 is probably as good as it gets for the short term at least. Benchmarks here: https://github.com/dsyer/java-function-benchmarks. TL;DR we can implement `Flux` functions without affecting performance, but possibly not with full dependency injection and Boot features.

**Comment by markfisher** [comment]
cool. nice work @dsyer !
